import type { GenerationAssetSlot, GenerationInputSchema, GenerationParameterField, JsonValue } from "@/contracts/generation";
import type { GenerationCapability, GenerationRoute } from "@/server/domain/generation";
import { QIANWEN_CREDENTIAL_REF, QIANWEN_PROVIDER_ID } from "./qianwen-provider-constants";
const MIB=1024*1024;
export const QIANWEN_WAN_3_TEXT_TO_VIDEO_OPERATION="wan-3-0-text-to-video";
export const QIANWEN_WAN_3_IMAGE_TO_VIDEO_OPERATION="wan-3-0-image-to-video";
export const QIANWEN_WAN_3_MULTIMODAL_VIDEO_OPERATION="wan-3-0-multimodal-video";
export type QianwenOperation=typeof QIANWEN_WAN_3_TEXT_TO_VIDEO_OPERATION|typeof QIANWEN_WAN_3_IMAGE_TO_VIDEO_OPERATION|typeof QIANWEN_WAN_3_MULTIMODAL_VIDEO_OPERATION;
export interface QianwenAssetBinding{slot:string;mediaType:"first_frame"|"last_frame"|"reference_image"|"reference_video"|"reference_audio";cardinality:"first"|"list"}
export interface QianwenExecutionConfig{protocol:"dashscope-media-v1";operation:QianwenOperation;endpointId:"video-synthesis";vendorModel:"wan3.0-video";requestProfile:"wan-3-video-v1";resultProfile:"video-url-v1";assetBindings:QianwenAssetBinding[];pollIntervalMs:15_000}
const params=():GenerationParameterField[]=>[
 select("resolution","分辨率",["480P","720P","1080P"],"1080P"),select("aspectRatio","画面比例",["adaptive","16:9","4:3","1:1","3:4","9:16"],"adaptive"),
 {key:"durationSeconds",label:"时长",description:"智能时长由模型根据输入决定。",type:"select",required:true,defaultValue:5,options:[{label:"智能时长",value:-1},...Array.from({length:29},(_,i)=>({label:`${i+2} 秒`,value:i+2}))]},
 bool("generateAudio","生成音轨",true),bool("promptExtend","提示词智能改写",true),bool("watermark","添加水印",false),
 {key:"seed",label:"随机种子",description:"留空时由供应商随机生成。",type:"number",min:0,max:2_147_483_647},
];
const slot=(key:string,label:string,mediaType:GenerationAssetSlot["mediaType"],maxFiles:number,maxFileSizeBytes:number,required=false):GenerationAssetSlot=>({key,label,mediaType,required,multiple:maxFiles>1,maxFiles,maxFileSizeBytes,acceptedTypes:mediaType==="image"?["image/png","image/jpeg","image/webp"]:mediaType==="video"?["video/mp4","video/quicktime"]:["audio/mpeg","audio/wav","audio/mp4"]});
const defs:Array<{operation:QianwenOperation;id:string;name:string;description:string;tags:string[];capability:GenerationCapability;schema:GenerationInputSchema;bindings:QianwenAssetBinding[]}>= [
 {operation:QIANWEN_WAN_3_TEXT_TO_VIDEO_OPERATION,id:"qianwen-wan-3-0-text-to-video",name:"Wan 3.0 文生视频",description:"千问AI平台 Wan 3.0 文生视频，支持 2–30 秒或智能时长、多种画幅、音轨生成与提示词智能改写。",tags:["最长30秒","智能时长","有声视频","最高1080P"],capability:"text-to-video",schema:{prompt:{required:true,maxLength:20_000},parameters:params()},bindings:[]},
 {operation:QIANWEN_WAN_3_IMAGE_TO_VIDEO_OPERATION,id:"qianwen-wan-3-0-image-to-video",name:"Wan 3.0 图生视频",description:"通过首帧或首尾帧生成 Wan 3.0 视频，素材经千问临时 OSS 安全提交。",tags:["首帧/首尾帧","最长30秒","有声视频","最高1080P"],capability:"image-to-video",schema:{prompt:{required:false,maxLength:20_000},parameters:params(),assets:[slot("firstFrameUrl","首帧图片","image",1,20*MIB,true),slot("lastFrameUrl","尾帧图片","image",1,20*MIB)]},bindings:[{slot:"firstFrameUrl",mediaType:"first_frame",cardinality:"first"},{slot:"lastFrameUrl",mediaType:"last_frame",cardinality:"first"}]},
 {operation:QIANWEN_WAN_3_MULTIMODAL_VIDEO_OPERATION,id:"qianwen-wan-3-0-multimodal-to-video",name:"Wan 3.0 多模态生视频",description:"组合参考图片、视频和音频生成 Wan 3.0 视频，并保持各类素材的稳定引用顺序。",tags:["多模态参考","图/视/音组合","最长30秒","有声视频"],capability:"multimodal-to-video",schema:{prompt:{required:true,maxLength:20_000},parameters:params(),assets:[slot("imageUrls","参考图片","image",10,20*MIB),slot("videoUrls","参考视频","video",5,50*MIB),slot("audioUrls","参考音频","audio",5,15*MIB)],constraints:[{kind:"at-least-one-asset",slots:["imageUrls","videoUrls","audioUrls"]}]},bindings:[{slot:"imageUrls",mediaType:"reference_image",cardinality:"list"},{slot:"videoUrls",mediaType:"reference_video",cardinality:"list"},{slot:"audioUrls",mediaType:"reference_audio",cardinality:"list"}]},
];
export function createQianwenRoutes(now=new Date().toISOString()):GenerationRoute[]{return defs.map(d=>({id:d.id,name:d.name,description:d.description,tags:d.tags,product:"Wan 3.0",capability:d.capability,providerId:QIANWEN_PROVIDER_ID,providerOperation:d.operation,enabled:false,isDefault:false,revision:2,defaults:Object.fromEntries((d.schema.parameters??[]).filter(f=>f.defaultValue!==undefined).map(f=>[f.key,f.defaultValue as JsonValue])),inputSchema:d.schema,adapterConfig:{protocol:"dashscope-media-v1",operation:d.operation,endpointId:"video-synthesis",vendorModel:"wan3.0-video",requestProfile:"wan-3-video-v1",resultProfile:"video-url-v1",assetBindings:d.bindings,pollIntervalMs:15_000} as unknown as JsonValue,credentialRef:QIANWEN_CREDENTIAL_REF,createdAt:now,updatedAt:now}));}
function select(key:string,label:string,values:Array<string|number>,defaultValue:string|number):GenerationParameterField{return{key,label,type:"select",required:true,defaultValue,options:values.map(value=>({label:String(value),value}))};}
function bool(key:string,label:string,defaultValue:boolean):GenerationParameterField{return{key,label,type:"boolean",defaultValue};}
