import type { GenerationAssetSlot, GenerationInputSchema, GenerationParameterField, JsonValue } from "@/contracts/generation";
import type { GenerationCapability, GenerationRoute } from "@/server/domain/generation";
import { QIANWEN_CREDENTIAL_REF, QIANWEN_PROVIDER_ID } from "./qianwen-provider-constants";
const MIB=1024*1024;
export const QIANWEN_WAN_3_TEXT_TO_VIDEO_OPERATION="wan-3-0-text-to-video";
export const QIANWEN_WAN_3_IMAGE_TO_VIDEO_OPERATION="wan-3-0-image-to-video";
export const QIANWEN_WAN_3_MULTIMODAL_VIDEO_OPERATION="wan-3-0-multimodal-video";
export const QIANWEN_Z_IMAGE_TEXT_TO_IMAGE_OPERATION="z-image-text-to-image";
export const QIANWEN_WAN_2_6_TEXT_TO_IMAGE_OPERATION="wan-2-6-text-to-image";
export type QianwenOperation=typeof QIANWEN_WAN_3_TEXT_TO_VIDEO_OPERATION|typeof QIANWEN_WAN_3_IMAGE_TO_VIDEO_OPERATION|typeof QIANWEN_WAN_3_MULTIMODAL_VIDEO_OPERATION;
export interface QianwenAssetBinding{slot:string;mediaType:"first_frame"|"last_frame"|"reference_image"|"reference_video"|"reference_audio";cardinality:"first"|"list"}
interface QianwenVideoExecutionConfig{protocol:"dashscope-media-v1";operation:QianwenOperation;endpointId:"video-synthesis";vendorModel:"wan3.0-video";requestProfile:"wan-3-video-v1";resultProfile:"video-url-v1";assetBindings:QianwenAssetBinding[];pollIntervalMs:15_000;submitMode:"async-task"}
interface QianwenImageExecutionConfig{protocol:"dashscope-media-v1";operation:typeof QIANWEN_Z_IMAGE_TEXT_TO_IMAGE_OPERATION|typeof QIANWEN_WAN_2_6_TEXT_TO_IMAGE_OPERATION;endpointId:"multimodal-generation"|"image-generation";vendorModel:"z-image-turbo"|"wan2.6-t2i";requestProfile:"messages-text-image-v1";resultProfile:"choices-content-image-v1";assetBindings:[];pollIntervalMs?:5_000;submitMode:"sync"|"async-task"}
export type QianwenExecutionConfig=QianwenVideoExecutionConfig|QianwenImageExecutionConfig;
const params=():GenerationParameterField[]=>[
 select("resolution","分辨率",["480P","720P","1080P"],"1080P"),select("aspectRatio","画面比例",["adaptive","16:9","4:3","1:1","3:4","9:16"],"adaptive"),
 {key:"durationSeconds",label:"时长",description:"智能时长由模型根据输入决定。",type:"select",required:true,defaultValue:5,options:[{label:"智能时长",value:-1},...Array.from({length:29},(_,i)=>({label:`${i+2} 秒`,value:i+2}))]},
 bool("generateAudio","生成音轨",true),bool("promptExtend","提示词智能改写",true),bool("watermark","添加水印",false),
 {key:"seed",label:"随机种子",description:"留空时由供应商随机生成。",type:"number",min:0,max:2_147_483_647},
];
const slot=(key:string,label:string,mediaType:GenerationAssetSlot["mediaType"],maxFiles:number,maxFileSizeBytes:number,required=false):GenerationAssetSlot=>({key,label,mediaType,required,multiple:maxFiles>1,maxFiles,maxFileSizeBytes,acceptedTypes:mediaType==="image"?["image/png","image/jpeg","image/webp"]:mediaType==="video"?["video/mp4","video/quicktime"]:["audio/mpeg","audio/wav","audio/mp4"]});
const defs:Array<{operation:QianwenOperation;id:string;name:string;description:string;tags:string[];capability:GenerationCapability;schema:GenerationInputSchema;bindings:QianwenAssetBinding[]}>= [
 {operation:QIANWEN_WAN_3_TEXT_TO_VIDEO_OPERATION,id:"qianwen-wan-3-0-text-to-video",name:"Wan 3.0 文生视频",description:"千问AI平台 Wan 3.0 文生视频，支持 2–30 秒或智能时长、多种画幅、音轨生成与提示词智能改写。",tags:["最长30秒","智能时长","有声视频","最高1080P"],capability:"text-to-video",schema:{prompt:{required:true,maxLength:20_000},parameters:params()},bindings:[]},
 {operation:QIANWEN_WAN_3_IMAGE_TO_VIDEO_OPERATION,id:"qianwen-wan-3-0-image-to-video",name:"Wan 3.0 图生视频",description:"通过首帧或首尾帧生成 Wan 3.0 视频，素材经千问临时 OSS 安全提交。",tags:["首帧/首尾帧","最长30秒","有声视频","最高1080P"],capability:"image-to-video",schema:{prompt:{required:false,maxLength:20_000},parameters:params(),assets:[slot("firstFrameUrl","首帧图片","image",1,20*MIB,true),slot("lastFrameUrl","尾帧图片","image",1,20*MIB)]},bindings:[{slot:"firstFrameUrl",mediaType:"first_frame",cardinality:"first"},{slot:"lastFrameUrl",mediaType:"last_frame",cardinality:"first"}]},
 {operation:QIANWEN_WAN_3_MULTIMODAL_VIDEO_OPERATION,id:"qianwen-wan-3-0-multimodal-to-video",name:"Wan 3.0 多模态生视频",description:"组合参考图片、视频和音频生成 Wan 3.0 视频，并保持各类素材的稳定引用顺序。",tags:["多模态参考","图/视/音组合","最长30秒","有声视频"],capability:"multimodal-to-video",schema:{prompt:{required:true,maxLength:20_000},parameters:params(),assets:[slot("imageUrls","参考图片","image",10,20*MIB),slot("videoUrls","参考视频","video",5,50*MIB),slot("audioUrls","参考音频","audio",5,15*MIB)],constraints:[{kind:"at-least-one-asset",slots:["imageUrls","videoUrls","audioUrls"]}]},bindings:[{slot:"imageUrls",mediaType:"reference_image",cardinality:"list"},{slot:"videoUrls",mediaType:"reference_video",cardinality:"list"},{slot:"audioUrls",mediaType:"reference_audio",cardinality:"list"}]},
];
export function createQianwenRoutes(now=new Date().toISOString()):GenerationRoute[]{return [...defs.map(d=>({id:d.id,name:d.name,description:d.description,tags:d.tags,product:"Wan 3.0",capability:d.capability,providerId:QIANWEN_PROVIDER_ID,providerOperation:d.operation,enabled:false,isDefault:false,revision:2,defaults:Object.fromEntries((d.schema.parameters??[]).filter(f=>f.defaultValue!==undefined).map(f=>[f.key,f.defaultValue as JsonValue])),inputSchema:d.schema,adapterConfig:{protocol:"dashscope-media-v1",operation:d.operation,endpointId:"video-synthesis",vendorModel:"wan3.0-video",requestProfile:"wan-3-video-v1",resultProfile:"video-url-v1",assetBindings:d.bindings,pollIntervalMs:15_000,submitMode:"async-task"} as unknown as JsonValue,credentialRef:QIANWEN_CREDENTIAL_REF,createdAt:now,updatedAt:now})),...imageRoutes(now)];}
function imageRoutes(now:string):GenerationRoute[]{const imageDefs=[{id:"qianwen-z-image-text-to-image",name:"Z-Image Turbo 文生图片",description:"千问 Z-Image Turbo 同步文生图，适合快速生成单张 PNG 图片。",tags:["同步生成","单张PNG","最高2048","提示词改写"],product:"Z-Image Turbo",operation:QIANWEN_Z_IMAGE_TEXT_TO_IMAGE_OPERATION,maxLength:800,model:"z-image-turbo",endpoint:"multimodal-generation",mode:"sync",size:"1024*1536",sizes:["1024*1024","832*1248","1248*832","864*1152","1152*864","720*1280","1280*720","1024*1536","1536*1024"]},{id:"qianwen-wan-2-6-text-to-image",name:"Wan 2.6 文生图片",description:"千问 Wan 2.6 异步文生图，支持 1–4 张输出、负向提示词和常用画幅。",tags:["异步生成","最多4张","多种画幅","提示词改写"],product:"Wan 2.6",operation:QIANWEN_WAN_2_6_TEXT_TO_IMAGE_OPERATION,maxLength:2100,model:"wan2.6-t2i",endpoint:"image-generation",mode:"async-task",size:"1280*1280",sizes:["1280*1280","1104*1472","1472*1104","960*1696","1696*960"]}] as const;return imageDefs.map(d=>{const fields:GenerationParameterField[]=[select("size","图片尺寸",[...d.sizes],d.size),bool("promptExtend","提示词智能改写",d.model!=="z-image-turbo"),...(d.model==="wan2.6-t2i"?[{key:"negativePrompt",label:"负向提示词",type:"text" as const,maxLength:500},{key:"imageCount",label:"生成数量",type:"number" as const,defaultValue:1,min:1,max:4},bool("watermark","添加水印",false)]:[]),{key:"seed",label:"随机种子",type:"number",min:0,max:2_147_483_647}];return{id:d.id,name:d.name,description:d.description,tags:[...d.tags],product:d.product,capability:"text-to-image",providerId:QIANWEN_PROVIDER_ID,providerOperation:d.operation,enabled:false,isDefault:false,revision:1,defaults:Object.fromEntries(fields.filter(f=>f.defaultValue!==undefined).map(f=>[f.key,f.defaultValue as JsonValue])),inputSchema:{prompt:{required:true,maxLength:d.maxLength},parameters:fields},adapterConfig:{protocol:"dashscope-media-v1",operation:d.operation,endpointId:d.endpoint,vendorModel:d.model,requestProfile:"messages-text-image-v1",resultProfile:"choices-content-image-v1",assetBindings:[],submitMode:d.mode,...(d.mode==="async-task"?{pollIntervalMs:5_000}:{})},credentialRef:QIANWEN_CREDENTIAL_REF,createdAt:now,updatedAt:now} as GenerationRoute;});}
function select(key:string,label:string,values:Array<string|number>,defaultValue:string|number):GenerationParameterField{return{key,label,type:"select",required:true,defaultValue,options:values.map(value=>({label:String(value),value}))};}
function bool(key:string,label:string,defaultValue:boolean):GenerationParameterField{return{key,label,type:"boolean",defaultValue};}
